dao: added UserDao and UserDaoImpl
vladverbytskyi/Cursor_Project_1 pull request #3
Opened 2020-01-14 18:30 UTC by Ronashovkova

Please check UserDao and UserDaoImpl

2020-01-14 18:49 UTC, MarDatsko commented on InternetShop/src/main/java/dao/UserDao.java
> +    void checkUserInDatabase(User user); //update
In my opinion, this method should just check if there is such a user in the database, and return true or false
boolean isUserInDatabase(User user);

2020-01-14 19:04 UTC, lazermann111 commented on InternetShop/src/main/java/dao/UserDao.java
> +    void setUserIntoDatabase(User user); //create
Tip: You may want to use save/create() names, they are more common

2020-01-14 19:04 UTC, lazermann111 commented on InternetShop/src/main/java/dao/UserDao.java
> +    void checkUserInDatabase(User user); //update
Tip: You may want to use update()

2020-01-14 19:07 UTC, lazermann111 requested changes
See comments

2020-01-14 19:07 UTC, lazermann111 commented on InternetShop/src/main/java/dao/UserDaoImpl.java
> +    private Map<String, User> users = new HashMap<>();
May be not obvious, but map should be static, otherwise, you may en up with lot of "database instances" in service/menu layers

2020-01-14 19:07 UTC, lazermann111 commented on InternetShop/src/main/java/dao/UserDaoImpl.java
> +    public Map<String, User> getAll() {
Passing map outside means anyone can change it, like, user from menu. I would either return copy of map or delete this method at all

2020-01-16 11:54 UTC, lazermann111 approved these changes

2020-01-16 19:59 UTC, lazermann111 approved these changes

2020-01-16 20:53 UTC, MarDatsko approved these changes

2020-01-17 11:05 UTC, merged