My order
vladverbytskyi/Cursor_Project_1 pull request #6
Opened 2020-01-27 16:50 UTC by MarDatsko

overridden method toString for Order, Product, PositionItem added opportunity print user order in window MyOrder

2020-01-27 20:27 UTC, lazermann111 commented on InternetShop/src/main/java/model/Order.java
> +        List<PositionItem> m = new ArrayList<>(getItemList());
no need to create array list here

2020-01-27 20:29 UTC, lazermann111 commented on InternetShop/src/main/java/view/impl/StartMenu.java
> +    private RegistrationMenu regMenu = new RegistrationMenu();
delete these menu, we have one in staticMenus

2020-01-27 20:30 UTC, lazermann111 commented on InternetShop/src/main/java/view/impl/OrderCheckoutMenu.java
> +
plz add implementation for all exit() and back() in all menus

2020-01-27 20:31 UTC, lazermann111 requested changes
plz fix comments

2020-01-28 10:53 UTC, lazermann111 approved these changes

2020-01-29 07:18 UTC, Ronashovkova approved these changes

2020-01-29 10:46 UTC, merged